### ISSUE TITLE
Twitter not fetching the profile picture

### ISSUE THREAD

**Issue by coldfumonkeh** [maksimkurb/multi-avatar#1]
Hi. I'm sending through a valid Twitter username but it's not returning, instead responding with an empty result:

`avatars { twitter: null }`

I've tried the URL directly in the browser and it works. Have you experienced this at all?

**Comment by maksimkurb** [comment]
It happened because of my haste, thanks :)

**Comment by coldfumonkeh** [comment]
Thank you for a quick fix :) Installing it shortly. Thanks for a great module too.
